parameters:
  publishFolder: '$(build.artifactstagingdirectory)'
  bicepConfigFolder: '' 
  artifactName: 'IACTemplates'
  flattenApplicationFolders: false
  applicationTemplatesFolder: 
  exclusions:

jobs:
- job: PublishApplicationIACTemplates
  displayName: Publish Application IAC templates to artifacts
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    clean: true

  - task: CopyFiles@2
    displayName: Copy Application IAC templates
    inputs:
      sourceFolder: '${{ parameters.applicationTemplatesFolder }}'
      contents: |
        **/*
        ${{ parameters.exclusions }}
        !**/.vscode/**/*.json
      targetFolder: '${{ parameters.publishFolder }}/IAC'
      flattenFolders: ${{ parameters.flattenApplicationFolders }}

  - ${{ if ne(parameters.bicepConfigFolder, '') }}:
    - task: CopyFiles@2
      displayName: Copy bicepconfig.json from '${{ parameters.bicepConfigFolder }}'
      inputs:
        sourceFolder: '${{ parameters.bicepConfigFolder }}'
        contents: |
          bicepconfig.json
        targetFolder: '${{ parameters.publishFolder }}/IAC'

  - task: PublishBuildArtifacts@1
    displayName: Publish '${{ parameters.publishFolder }}/IAC' to pipeline artifacts
    inputs:
      pathToPublish: '${{ parameters.publishFolder }}/IAC'
      artifactName: 'Application_${{ parameters.artifactName }}'
      artifactType: container
