parameters:
  publishFolder: '$(build.artifactstagingdirectory)'
  artifactName: 'IACTemplates'
  flattenApplicationFolders: false
  applicationTemplatesFolder: 
  jsonFilter: '**/*.json'

jobs:
- job: PublishApplicationIACTemplates
  displayName: Publish Application IAC templates to artifacts
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    clean: true

  - task: CopyFiles@2
    displayName: Copy Application IAC templates
    inputs:
      sourceFolder: '${{ parameters.applicationTemplatesFolder }}'
      contents: |
        **/*.ps1
        **/*.psm1
        **/*.IAC
        ${{ parameters.jsonFilter }}
        !**/.vscode/**/*.json
      targetFolder: '${{ parameters.publishFolder }}/IAC'
      flattenFolders: ${{ parameters.flattenApplicationFolders }}

  - task: PublishBuildArtifacts@1
    displayName: Publish '${{ parameters.publishFolder }}/IAC' to pipeline artifacts
    inputs:
      pathToPublish: '${{ parameters.publishFolder }}/IAC'
      artifactName: 'Application_${{ parameters.artifactName }}'
      artifactType: container
