parameters:
  publishFolder: '$(build.artifactstagingdirectory)'
  artifactName: 'IACTemplates'
  flattenApplicationFolders: false
  applicationTemplatesFolder: 
  exclusions:  # Exclusion lines should be preceded with !  / Exclusion can be made multiline by writing a pipe ->  exclusions: | \n !**\*.ps1 

jobs:
- job: PublishApplicationIACTemplates
  displayName: Publish Application IAC templates to artifacts
  steps:
  - checkout: self
    clean: true

  - task: CopyFiles@2
    displayName: Copy Application IAC templates
    inputs:
      sourceFolder: '${{ parameters.applicationTemplatesFolder }}'
      contents: |
        **/*
        ${{ parameters.exclusions }}
        !**/.vscode/**/*.json
      targetFolder: '${{ parameters.publishFolder }}/IAC'
      flattenFolders: ${{ parameters.flattenApplicationFolders }}

  - task: PublishBuildArtifacts@1
    displayName: Publish '${{ parameters.publishFolder }}/IAC' to pipeline artifacts
    inputs:
      pathToPublish: '${{ parameters.publishFolder }}/IAC'
      artifactName: 'Application_${{ parameters.artifactName }}'
      artifactType: container
