# This pipeline creates a new repo in an Azure Devops Team Project Collection, based on an existing repo in the same Team Project Collection. 
# It emulates the same functionality as Github's template repositories.
# Note: it only works within Azure Devops. Creating a new repo from an existing Github repo is currently not supported. 

# Installation
# - Add the pipeline to Azure Devops.  
# - Line 31: Replace "!BaseRepo" with the name of the default template repo in your Team Project Collection.

# Usage
# Run the pipeline from Azure Devops. It has some required parameters to specify the source and target repo. After running, a new repo will have been added.  
#
# The new repo will be identical to the existing repo, but: 
# - Only one branch will be cloned
# - All on the source repo commits will be reset into 1 single initial commit on the new repo

# Credits
# This pipeline is inspired by (and partially based on) a blogpost from Stephen Allwright. 
# https://stephenallwright.com/project-template-repository-azure-devops/

name: "Create new repo '${{ parameters.newRepoName }}'"
# Commit message on source repo has nothing to do with the run. Do not display.
appendCommitMessageToRunName: false

parameters:
- name: 'newRepoName'
  type: string
  displayName: 'Name of the new repository'
- name: 'templateRepo'
  type: string
  displayName: 'Template repository: GIT url, OR repository name within this Team Project Collection'
  default: "https://github.com/ArnoPeters/BaseRepo-AzDO-CSharp"
- name: 'templateRepoBranch'
  displayName: 'Source branch from the template repository'
  type: string
  default: 'main'

trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

jobs:
- job: 
  displayName: "Create new repository '${{ parameters.newRepoName }}' from template @ '${{ parameters.templateRepo }}'"
  steps:
  - checkout: none
  - bash: |
      sourceRepo='${{ parameters.templateRepo }}'
      userName='$(Build.RequestedFor)'
      userEmail='$(Build.RequestedForEmail)'
      project='$(System.TeamProject)'
      projectUriEscaped=$(jq -rn --arg x "${project}" '$x|@uri')
      collectionUrl='$(System.CollectionUri)'
      sourceBranch='${{ parameters.templateRepoBranch }}'
      workingDir='$(Build.SourcesDirectory)'
      newRepoName='${{ parameters.newRepoName }}'
      newRepoPrefix="${collectionUrl}${projectUriEscaped}/_git/"
      
      if [[ "${sourceRepo}" =~ ^"http" ]]; then
        sourceRepoUrl="${sourceRepo}"
      else
        only uri encode if only repo name. 
        sourceRepoName=$(jq -rn --arg x "${sourceRepo}" '$x|@uri')
        sourceRepoUrl="${newRepoPrefix}${sourceRepoName}"
      fi
            
      # Login to DevOps using your system access token
      echo $(System.AccessToken) | az devops login

      # pre-flight check if new repo does not already exists.
      cmd=("az repos list --organization \"${collectionUrl}\" --project \"${project}\"")
      #out=$(eval "$cmd")
      repoAlreadyExists=$(eval "$cmd" | jq -e ".[] | select(.name == \"${newRepoName}\")")
      
      if [[ "$repoAlreadyExists" != "" ]]; then
        echo "##[error]Repository '${newRepoName}' already exists. Aborting."  
      else
        echo "##[debug]Setting extra header for '${newRepoPrefix}'."
        #assumption: org has been switched to use new dev.azure.com urls - if accessed by new url but not switched, this global config will not add the correct prefixes. 
        git config --global --add "http.$newRepoPrefix.extraHeader" "Authorization: Bearer $(System.AccessToken)"

        # Clone the template repo to the agent. Using the extraheader solves the problem of having to alter the url. 
        echo "##[debug]Cloning template repository."
        git clone "${sourceRepoUrl}" \
          -b "${sourceBranch}" \
          --single-branch \
          --no-tags \
          "${workingDir}"
        
        # Mixed reset to first commit, then push with amend.
        # NOTE: .git folder is NOT removed! This is to keep modules and other settings working properly.
        echo "##[debug]Resetting commits before upload."
        initialCommitSha=$(git rev-list --max-parents=0 --abbrev-commit HEAD)
        git reset --mixed $initialCommitSha
        
        # Recommit everything in the repo, replacing the first commit with whatever the template repo provides. 
        # NOTE: requires one time use of name / email. Does not need to go in agent global config. 
        echo "##[debug]Adding files and creating new initial commit."
        git add --all 
        git -c user.name="${userName}" -c user.email="${userEmail}"  commit --amend  -m "Copied from template repo '${sourceRepo}'"

        # Create new empty repo
        echo "##[debug]Creating new repository in Azure Devops"
        az repos create --name "${newRepoName}" --organization "${collectionUrl}" --project "${project}"

        # Add the new remote. Original remote is kept as 'template'
        # And push everything into the new repo.
        echo "##[debug]Pushing source to new repository."
        git remote rename origin template
        git remote add origin "${newRepoPrefix}${newRepoName}"
        git push -u origin --all 
      fi
    displayName: 'Replicate repository based on template'
    